# Generated by Django 5.0.3 on 2024-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ("Driver's License Number", "Driver's License Number"), ('National Identications Number', 'National Identity Number'), ('Passport Number', 'Passport Number')], max_length=200, null=True),
        ),
    ]
