# Generated by Django 5.0.3 on 2024-04-12 09:48

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_success_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
    ]
